# AWS S3 Storage Configuration
flysystem:
    storages:
        default.storage:
            adapter: 'aws'
            options:
                client: 'aws.s3_client'
                bucket: '%env(AWS_S3_BUCKET)%'
                prefix: '%env(AWS_S3_PREFIX)%'
