version: '3'

services:
  php:
    container_name: mapinha-php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - setup-mapinha_network

  nginx:
    container_name: mapinha-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - setup-mapinha_network

  postgres:
    container_name: mapinha-postgres
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    tty: true
    volumes:
      - setup-data:/var/lib/postgresql/data:rw
      - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - setup-mapinha_network
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}" ]
      timeout: 5s
      retries: 5
      start_period: 60s

networks:
  setup-mapinha_network:
    driver: bridge

volumes:
  setup-data:
