version: '3'

services:
  php:
    container_name: secult-php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - setup-secult_network

  nginx:
    container_name: secult_nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - setup-secult_network

  postgres:
    container_name: secult_postgres
    image: postgres:13
    restart: always
    tty: true
    volumes:
      - setup-data:/var/lib/postgresql/data
      - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - setup-secult_network
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: db_secult
      POSTGRES_USER: secult
      POSTGRES_PASSWORD: meianoiteeuteconto

networks:
  setup-secult_network:
    driver: bridge

volumes:
  setup-data:
