name: Minha Casa Melhor
author: Secretaria Nacional de Periferias
email: emaildasecretaria@email
logo:
  horizontal:
    path: /img/regmel/regmel-logo.svg
    width: 100px
  vertical:
    path: /img/regmel/regmel-logo.svg
    width: 200px
modules:
  organizations: Municípios
  agents: Agentes Promotores
  opportunities: Credenciamento
  events:
  spaces:
  initiatives:

navbar:
  web_home_homepage:
    text: home
    icon: home
    color: "#224638"
  web_opportunity_list:
    text: Adesão e Proposta
    icon: description
    color: "#F59E00"
  web_faq_faq:
    text: Perguntas Frequentes
    icon: quiz
    color: "#E70DCB"

dropdown:
  control_panel:
    title: 'control_panel'
    enabled: true
    items:
      - text: 'control_panel'
        icon: 'touch_app'
        route: 'admin_dashboard'

  management:
    title: 'management'
    enabled: true
    items:
#      - text: 'agents'
#        icon: 'group'
#        route: 'admin_agent_list'
#      - text: 'opportunities'
#        icon: 'lightbulb'
#        route: 'admin_opportunity_list'
#      - text: 'organizations'
#        icon: 'corporate_fare'
#        route: 'admin_organization_list'


dashboard:
  cards:
    agents:
      title: Agentes Promotores
      icon: group
      color: "#F59E00"
      route_create: "admin_agent_create"
      total_key: totalAgents
    opportunities:
      title: Credenciamento
      icon: lightbulb
      color: "#E70DCB"
      route_create: "admin_opportunity_create"
      total_key: totalOpportunities
    organizations:
      title: Municípios
      icon: corporate_fare
      color: "#6A5ACD"
      route_create: "admin_organization_add"
      total_key: totalOrganizations
    Teste1:
      title: Teste 1
      icon: corporate_fare
      color: "#6A5ACD"
      route_create: "admin_organization_add"
      total_key: totalOrganizations
    Test2:
      title: Teste 2
      icon: corporate_fare
      color: "#6A5ACD"
      route_create: "admin_organization_add"
      total_key: totalOrganizations
  inscriptions_area: false

sidebar:
  dashboard:
    title: menu
    items:
      admin_dashboard:
        icon: dashboard
        text: control_panel
        color: text-info

  my_opportunities:
    title: Anuencia
    items:
      admin_registration_list:
        icon: app_registration
        text: my_subscriptions
#      admin_accountability_list:
#        icon: payments
#        text: accountability

  notice_opportunity:
    title: footer.notices_opportunities
    items:
      admin_opportunity_list:
        icon: diversity_2
        text: Credenciamento
      admin_review_list:
        icon: manage_search
        text: my_reviews

  entity:
    title: management
    items:
      admin_agent_list:
        icon: people
        text: Agentes Promotores
#      admin_event_list:
#        icon: event
#        text: my_events
#      admin_space_list:
#        icon: apartment
#        text: my_spaces
      admin_initiative_list:
        icon: article
        text: Propostas
#      admin_organization_list:
#        icon: place
#        text: Municipios

  admin:
    title: admin_options
    items:
#      admin_seal_list:
#        icon: bookmark
#        text: seals
#      admin_subsite_list:
#        icon: account_tree
#        text: subsites
      admin_user_list:
        icon: manage_accounts
        text: users
      admin_faq_list:
        icon: quiz
        text: faq
      admin_role_list:
        icon: newspaper
        text: functions
      admin_regmel_company_list:
        icon: business
        text: Empresas/OSC
      admin_regmel_municipality_list:
        icon: location_city
        text: Municípios

homepage:
  sections:
    header:
      enabled: false
      title: Minha Casa Melhor
      subtitle: subtitulo aqui
      action:
        route: regmel_about
        title: SAIBA MAIS
      description: descricao aqui
      background: bg-dark
      image: img/regmel.svg
      image_width: 70%
    banner:
      enabled: true
      image: /img/regmel/minha-casa-melhor-banner.svg
    register:
      enabled: true
      color: "#1c8230"
      options:
        municipio:
          title: Município
          route: regmel_register_city
        empresa:
          title: Empresa/OSC
          route: regmel_register_company
    opportunities:
      enabled: false
    modules:
      enabled: false
    happen_now:
      enabled: false
    maps:
      enabled: false
      background: bg-dark
      color: text-light
    contribute:
      enabled: false
    footer:
      discover: false
      control_panel: false
      help: true
