list:
  path: /municipios
  controller: App\Controller\Web\OrganizationWebController::list
  methods: ['GET']

getOne:
  path: /municipios/{id}
  controller: App\Controller\Web\OrganizationWebController::getOne
  methods: ['GET']